/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BestSeason { 'endMonth' : string, 'startMonth' : string }
export type Category = { 'spiritual' : null } |
  { 'cultural' : null } |
  { 'adventure' : null } |
  { 'wildlife' : null } |
  { 'beach' : null };
export interface Destination {
  'region' : string,
  'name' : string,
  'description' : string,
  'bestSeason' : BestSeason,
}
export interface Inquiry {
  'id' : bigint,
  'destinationOfInterest' : string,
  'name' : string,
  'travelDates' : string,
  'email' : string,
  'numberOfTravelers' : bigint,
  'message' : string,
  'phone' : string,
}
export interface Testimonial {
  'name' : string,
  'reviewText' : string,
  'rating' : bigint,
  'location' : string,
  'tourPackageName' : string,
}
export interface TourPackage {
  'durationDays' : bigint,
  'destination' : string,
  'name' : string,
  'highlights' : Array<string>,
  'category' : Category,
  'priceINR' : bigint,
}
export interface _SERVICE {
  'addInquiry' : ActorMethod<[Inquiry], bigint>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'getDestinations' : ActorMethod<[], Array<Destination>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTourPackages' : ActorMethod<[], Array<TourPackage>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];