/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'destinationOfInterest' : IDL.Text,
  'name' : IDL.Text,
  'travelDates' : IDL.Text,
  'email' : IDL.Text,
  'numberOfTravelers' : IDL.Nat,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
  'location' : IDL.Text,
  'tourPackageName' : IDL.Text,
});
export const BestSeason = IDL.Record({
  'endMonth' : IDL.Text,
  'startMonth' : IDL.Text,
});
export const Destination = IDL.Record({
  'region' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'bestSeason' : BestSeason,
});
export const Category = IDL.Variant({
  'spiritual' : IDL.Null,
  'cultural' : IDL.Null,
  'adventure' : IDL.Null,
  'wildlife' : IDL.Null,
  'beach' : IDL.Null,
});
export const TourPackage = IDL.Record({
  'durationDays' : IDL.Nat,
  'destination' : IDL.Text,
  'name' : IDL.Text,
  'highlights' : IDL.Vec(IDL.Text),
  'category' : Category,
  'priceINR' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addInquiry' : IDL.Func([Inquiry], [IDL.Nat], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'destinationOfInterest' : IDL.Text,
    'name' : IDL.Text,
    'travelDates' : IDL.Text,
    'email' : IDL.Text,
    'numberOfTravelers' : IDL.Nat,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
    'location' : IDL.Text,
    'tourPackageName' : IDL.Text,
  });
  const BestSeason = IDL.Record({
    'endMonth' : IDL.Text,
    'startMonth' : IDL.Text,
  });
  const Destination = IDL.Record({
    'region' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'bestSeason' : BestSeason,
  });
  const Category = IDL.Variant({
    'spiritual' : IDL.Null,
    'cultural' : IDL.Null,
    'adventure' : IDL.Null,
    'wildlife' : IDL.Null,
    'beach' : IDL.Null,
  });
  const TourPackage = IDL.Record({
    'durationDays' : IDL.Nat,
    'destination' : IDL.Text,
    'name' : IDL.Text,
    'highlights' : IDL.Vec(IDL.Text),
    'category' : Category,
    'priceINR' : IDL.Nat,
  });
  
  return IDL.Service({
    'addInquiry' : IDL.Func([Inquiry], [IDL.Nat], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'getDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };